<?php
namespace App\Console\Commands;

use App\Models\Locatie;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class ExportLocationAssets extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:export-location-assets';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Export location images to frontend assets with sector-prefixed naming and generate a fallback bash script';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Initializing location asset export...');

        try {
            $locaties = Locatie::with(['artwork', 'scenes.sector'])->get();
        } catch (\Exception $e) {
            $this->error('Database connection failed. Are you running this inside the correct environment?');
            $this->error($e->getMessage());
            return Command::FAILURE;
        }

        if ($locaties->isEmpty()) {
            $this->error('No locations found in database.');
            return Command::FAILURE;
        }

        $projectRoot        = base_path('..');
        $frontendAssetsPath = $projectRoot . '/frontend/assets/locations/images';
        $bashScriptPath     = base_path('export_location_images.sh');

        $scriptLines = [
            "#!/bin/bash",
            "# Automatically generated by php artisan app:export-location-assets",
            "echo \"Starting asset export...\"",
            "echo \"Target directory: frontend/assets/locations/images/\"",
            "",
        ];

        $copyCount   = 0;
        $scriptCount = 0;

        foreach ($locaties as $locatie) {
            $artwork = $locatie->artwork->first();
            if (! $artwork) {
                $this->line("Skipping {$locatie->naam}: No artwork found.");
                continue;
            }

            // Path to source image (usually relative to storage/app/public)
            $bestandspad        = ltrim($artwork->bestandspad, '/');
            $sourceRelativePath = 'storage/app/public/' . $bestandspad;
            $sourceFullPath     = base_path($sourceRelativePath);

            // Backup source path if it uses the public/storage symlink path logic
            $sourcePublicPath = public_path('storage/' . $bestandspad);

            // Get unique sectors from all scenes associated with this location
            $sectors = $locatie->scenes->map(fn($s) => $s->sector)->filter()->unique('id');

            if ($sectors->isEmpty()) {
                $this->line("Skipping {$locatie->naam}: No sectors associated via scenes.");
                continue;
            }

            foreach ($sectors as $sector) {
                // Formatting: {sector}--{location-name}.png in lowercase
                $sectorSlug     = Str::slug($sector->naam);
                $locationSlug   = Str::slug($locatie->naam);
                $targetFileName = "{$sectorSlug}--{$locationSlug}.png";
                $targetFullPath = "{$frontendAssetsPath}/{$targetFileName}";

                // 1. Add to bash script (relative to project root)
                $scriptLines[] = "echo \"  Processing: {$targetFileName}\"";
                $scriptLines[] = "cp -n \"backend/public/storage/{$bestandspad}\" \"frontend/assets/locations/images/{$targetFileName}\"  ";
                $scriptCount++;

                // 2. Try direct copy if possible (running on host)
                // We only attempt this if the frontend directory is actually writable to avoid Docker permission errors
                if (is_writable(dirname($frontendAssetsPath))) {
                    if (File::exists($sourceFullPath)) {
                        File::ensureDirectoryExists($frontendAssetsPath);
                        if (File::copy($sourceFullPath, $targetFullPath)) {
                            $copyCount++;
                        }
                    } elseif (File::exists($sourcePublicPath)) {
                        File::ensureDirectoryExists($frontendAssetsPath);
                        if (File::copy($sourcePublicPath, $targetFullPath)) {
                            $copyCount++;
                        }
                    }
                }

            }
        }

        // Write bash script
        $scriptLines[] = "";
        $scriptLines[] = "echo \"\"";
        $scriptLines[] = "echo \"Export complete. Total assets defined: {$scriptCount}\"";

        try {
            File::put($bashScriptPath, implode("\n", $scriptLines));
            @chmod($bashScriptPath, 0755);
        } catch (\Exception $e) {
            $this->error("Failed to write bash script: " . $e->getMessage());
        }

        $this->info("Success!");
        $this->info("- Direct copies performed: {$copyCount} (only if frontend folder was accessible)");
        $this->info("- Bash script generated: {$bashScriptPath}");
        $this->info("- Total operations mapped in script: {$scriptCount}");

        $this->warn("\nTIP: Since Docker usually separates Backend and Frontend volumes, the direct copy may have skipped some files.");
        $this->warn("Please run the generated script from your main project root (on your host terminal):");
        $this->line("cd " . $projectRoot);
        $this->line("bash backend/export_location_images.sh");

        return Command::SUCCESS;
    }
}
